name: T2VZeroNew
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - pip
  - cudatoolkit
  - pytorch
  - torchvision
  - pip:
      - gradio
      - albumentations
      - opencv-contrib-python
      - imageio
      - imageio-ffmpeg
      - pytorch-lightning
      - omegaconf
      - test-tube
      - streamlit
      - einops
      - transformers
      - webdataset
      - kornia open_clip_torch
      - invisible-watermark
      - streamlit-drawable-canvas
      - torchmetrics
      - timm
      - addict
      - yapf
      - prettytable
      - safetensors
      - basicsr
      - accelerate
      - decord
      - diffusers
      - moviepy
      - opencv_python
      - Pillow
      - scikit_image
      - scipy
      - tensorboardX tqdm
      - numpy
